apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ecommerce-platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: ecommerce-platform
    app.kubernetes.io/part-of: ecommerce
spec:
  description: E-commerce platform microservices project
  
  # Source repositories
  sourceRepos:
  - 'https://github.com/your-org/ecommerce-k8s-platform'
  - 'https://charts.bitnami.com/bitnami'
  - 'https://prometheus-community.github.io/helm-charts'
  - 'https://grafana.github.io/helm-charts'
  - 'https://elastic.github.io/helm-charts'
  
  # Destination clusters and namespaces
  destinations:
  - namespace: ecommerce
    server: https://kubernetes.default.svc
  - namespace: ecommerce-dev
    server: https://kubernetes.default.svc
  - namespace: ecommerce-staging
    server: https://kubernetes.default.svc
  - namespace: ecommerce-prod
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  - namespace: logging
    server: https://kubernetes.default.svc
  - namespace: jenkins
    server: https://kubernetes.default.svc
  
  # Cluster resource whitelist
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: ''
    kind: PersistentVolume
  - group: storage.k8s.io
    kind: StorageClass
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
  
  # Namespace resource whitelist
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: ''
    kind: ServiceAccount
  - group: ''
    kind: PersistentVolumeClaim
  - group: apps
    kind: Deployment
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: DaemonSet
  - group: apps
    kind: ReplicaSet
  - group: batch
    kind: Job
  - group: batch
    kind: CronJob
  - group: networking.k8s.io
    kind: Ingress
  - group: networking.k8s.io
    kind: NetworkPolicy
  - group: policy
    kind: PodDisruptionBudget
  - group: autoscaling
    kind: HorizontalPodAutoscaler
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
  - group: metrics.k8s.io
    kind: PodMetrics
  
  # Roles for project members
  roles:
  - name: admin
    description: Admin access to ecommerce platform
    policies:
    - p, proj:ecommerce-platform:admin, applications, *, ecommerce-platform/*, allow
    - p, proj:ecommerce-platform:admin, repositories, *, *, allow
    - p, proj:ecommerce-platform:admin, clusters, *, *, allow
    groups:
    - ecommerce-platform:admin
  
  - name: developer
    description: Developer access to ecommerce platform
    policies:
    - p, proj:ecommerce-platform:developer, applications, get, ecommerce-platform/*, allow
    - p, proj:ecommerce-platform:developer, applications, sync, ecommerce-platform/*, allow
    - p, proj:ecommerce-platform:developer, repositories, get, *, allow
    groups:
    - ecommerce-platform:developer
  
  - name: readonly
    description: Read-only access to ecommerce platform
    policies:
    - p, proj:ecommerce-platform:readonly, applications, get, ecommerce-platform/*, allow
    - p, proj:ecommerce-platform:readonly, repositories, get, *, allow
    groups:
    - ecommerce-platform:readonly
