apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
  labels:
    name: ecommerce
    app.kubernetes.io/name: ecommerce-platform
    app.kubernetes.io/part-of: ecommerce
---
apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-dev
  labels:
    name: ecommerce-dev
    app.kubernetes.io/name: ecommerce-platform
    app.kubernetes.io/part-of: ecommerce
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-staging
  labels:
    name: ecommerce-staging
    app.kubernetes.io/name: ecommerce-platform
    app.kubernetes.io/part-of: ecommerce
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-prod
  labels:
    name: ecommerce-prod
    app.kubernetes.io/name: ecommerce-platform
    app.kubernetes.io/part-of: ecommerce
    environment: production
